name       : mousepad
version    : 0.6.1
release    : 1
source     :
    - https://archive.xfce.org/src/apps/mousepad/0.6/mousepad-0.6.1.tar.bz2 : 560c5436c7bc7de33fbf3e9f6cc545280772ad898dfb73257d86533880ffff36
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Mousepad is a simple text editor for the Xfce desktop environment..
description: |
    Mousepad is a simple text editor for the Xfce desktop environment.
builddeps  :
    - pkgconfig(gtksourceview-4)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
